services:
  pxe-server:
    build:
      context: .
    container_name: pxe-server
    ports:
      - "67:67/udp"
      - "69:69/udp"
    networks:
      pxe_net:
        ipv4_address: 192.168.100.10  # Assign static IP
    environment:
      -  MIN_DOWNLOADS=${MIN_DOWNLOADS:-5}
    volumes:
      - ./pxe-data:/var/lib/tftpboot
    entrypoint: ["/start.sh"]

networks:
  pxe_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
